In [1]:
# Name: - L Prathyusha

In [2]:
import numpy as np

In [3]:
a = np.array([2, 4, 6])
b = a[0:2]
print(b)

[2 4]


In [4]:
import numpy as np

a = np.array([2, 4, 6, 8])
print(a)
b = a[1:]
print(b)

[2 4 6 8]
[4 6 8]


In [5]:
a = np.array([2, 4, 6, 8])
b = a[0:4]
print(b)
c = a[:4]
print(c)
d = a[0:]
print(d)
e = a[:]
print(e)

[2 4 6 8]
[2 4 6 8]
[2 4 6 8]
[2 4 6 8]


In [6]:
a = np.array([[2, 4, 6, 8], [10, 20, 30, 40]])
b = a[:,:]  #[all rows, all columns]
print(b)

[[ 2  4  6  8]
 [10 20 30 40]]
